# Generated by Django 4.0.4 on 2022-04-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_quest', to='api.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_railway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_vid', to='api.railway'),
        ),
    ]
