# Generated by Django 4.0.4 on 2022-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='railway',
            name='description',
            field=models.CharField(blank=True, default='', max_length=650),
        ),
    ]
